### ISSUE TITLE
ACCO

### ISSUE THREAD

**Issue by mariagrandury** [EleutherAI/polyglot-data#28]

**Comment by dongin1009** [comment]
I downloaded the raw file of ACCO to `fr` through wget. So, there is not download script.

**Comment by dongin1009** [comment]
Download from here: [https://echanges.dila.gouv.fr/OPENDATA/ACCO/](https://echanges.dila.gouv.fr/OPENDATA/ACCO/)
The extraction and merging script is [here](https://github.com/EleutherAI/polyglot-data/commit/051c730d66a09e28efdfe3a5e62b6ff80632d3df).
