### ISSUE TITLE
OSCAR

### ISSUE THREAD

**Issue by hyunwoongko** [EleutherAI/polyglot-data#6]

**Comment by josemlopez** [comment]
Spanish has been downloaded in `/fsx/polyglot_data/romance/es/0_raw/OSCAR/`. 
However, I have observed that we are running out of space on the disk.

`cp: error writing ‘/fsx/polyglot_data/romance/es/0_raw/OSCAR/oscar-2201-train.arrow’: No space left on device
cp: failed to extend ‘/fsx/polyglot_data/romance/es/0_raw/OSCAR/oscar-2201-train.arrow’: No space left on device`

Spanish OSCAR dataset is massive: 

`
-rw-r--r-- 1 jlopez Domain Users  68K Nov 13 18:59 dataset_info.json
-rw-r--r-- 1 jlopez Domain Users 311G Nov 13 18:59 oscar-2201.arrow
`

**Comment by josemlopez** [comment]
This was finished. 
Arrow format was acceptable after all.
